# Generated by Django 4.0.6 on 2022-07-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/messenger/chat_photos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/messenger/profile_photos'),
        ),
    ]
