# Generated by Django 4.0.6 on 2022-07-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0006_remove_profile_avatar_chat_photo_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/messenger/chat_photos'),
        ),
    ]
