# Generated by Django 4.2.1 on 2023-05-26 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0008_group_chat_creator_chat_type_profile_is_teacher_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Student group', 'verbose_name_plural': 'Student groups'},
        ),
        migrations.AddField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.group'),
        ),
    ]
