# Generated by Django 4.2.1 on 2023-06-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0010_message_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
