# Generated by Django 4.2.1 on 2023-06-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0012_profile_diploma_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магістр')], max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='department',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='institute',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='speciality',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='study_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
