# Generated by Django 4.2.1 on 2023-06-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0013_group_degree_group_department_group_institute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='department',
            new_name='faculty',
        ),
    ]
