# Generated by Django 4.2.1 on 2023-06-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0015_rename_middle_name_profile_patronymic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diploma_reviewer_position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
