# Generated by Django 4.2.1 on 2023-06-14 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0016_profile_diploma_reviewer_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to='static/messenger/document_templates', verbose_name='Файл шаблону')),
                ('name', models.CharField(max_length=255, verbose_name='Назва шаблону')),
                ('button_text', models.CharField(max_length=255, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Шаблон документів',
                'verbose_name_plural': 'Шаблони документів',
            },
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name': 'Чат', 'verbose_name_plural': 'Чати'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Група', 'verbose_name_plural': 'Групи'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Творець чату'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва чату'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/messenger/chat_photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('private', 'приватний'), ('group', 'груповий'), ('diploma', 'дипломний')], default='group', max_length=255, verbose_name='Тип чату'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='users',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL, verbose_name='Користувачі'),
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код групи'),
        ),
        migrations.AlterField(
            model_name='group',
            name='degree',
            field=models.CharField(blank=True, choices=[('bachelor', 'бакалавр'), ('master', 'магістр')], max_length=255, verbose_name='Ступінь'),
        ),
        migrations.AlterField(
            model_name='group',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='group',
            name='institute',
            field=models.CharField(blank=True, max_length=255, verbose_name='Інститут'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва групи'),
        ),
        migrations.AlterField(
            model_name='group',
            name='speciality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='group',
            name='study_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messenger.chat', verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/messenger/message_files', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер повідомлення'),
        ),
        migrations.AlterField(
            model_name='message',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='Закріплено'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='Текст повідомлення'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата надсилання'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Про себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diploma_reviewer',
            field=models.CharField(blank=True, max_length=255, verbose_name='Рецензент'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diploma_reviewer_position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада рецензента'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diploma_supervisor_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Керівник диплому 1'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diploma_supervisor_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Керівник диплому 2'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='diploma_topic',
            field=models.CharField(blank=True, max_length=255, verbose_name='Тема диплому'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Підтвердження пошти'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='messenger.group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_teacher',
            field=models.BooleanField(default=False, verbose_name='Є викладачем'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, verbose_name='По-батькові'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/messenger/profile_photos', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('chat', 'number')},
        ),
    ]
