# Generated by Django 4.2.1 on 2023-06-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0017_documenttemplate_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Назва шаблону'),
        ),
    ]
