# Generated by Django 4.2.1 on 2023-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0018_alter_documenttemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='information',
            field=models.TextField(blank=True, default='{\n    "links": [\n        {"опис": "посилання"},\n    ]\n}', verbose_name='Інформація'),
        ),
    ]
