# Generated by Django 4.2.1 on 2023-06-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0019_group_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='methodological_guide',
            field=models.FileField(blank=True, upload_to='static/messenger/methodological_guides', verbose_name='Методичні вказівки'),
        ),
    ]
