# Generated by Django 4.2.1 on 2023-06-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0020_group_methodological_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='information',
            field=models.TextField(blank=True, help_text='123', verbose_name='Інформація'),
        ),
    ]
